# -*- coding: utf-8 -*-
"""test_csv_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cuN5ULwa7VwypyqOqdMCqyfkkk2TsSxT
"""

import pandas as pd

# Sample test data
data = {
    "id": ["00006", "00007", "00008", "00009", "00010"],
    "comment_text": [
        "I appreciate your work!",
        "This is so dumb.",
        "You are amazing!",
        "Shut up and go away!",
        "What a great day!"
    ]
}

# Create DataFrame
df_test = pd.DataFrame(data)

# Save to CSV
df_test.to_csv("test.csv", index=False)