# -*- coding: utf-8 -*-
"""train_csv_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HWIPmInAEOXjDgY9-tVeIQNln37qHcgf
"""

import pandas as pd

# Sample training data
data = {
    "id": ["00001", "00002", "00003", "00004", "00005"],
    "comment_text": [
        "You are so stupid!",
        "I love this community.",
        "This is the worst thing ever!",
        "Thank you for your help!",
        "Get lost, idiot!"
    ],
    "toxic": [1, 0, 1, 0, 1]  # 1 = toxic, 0 = non-toxic
}

# Create DataFrame
df_train = pd.DataFrame(data)

# Save to CSV
df_train.to_csv("train.csv", index=False)